-- Total Number of Products in Each Category
SELECT category, COUNT(*) as total_products
FROM Products
GROUP BY category;

-- Total Revenue Generated by the Store
SELECT SUM(total_amount) as total_revenue
FROM Orders;

-- Top 5 Customers by Total Spending
SELECT c.customer_name, SUM(o.total_amount) AS total_spending
FROM Customers c
INNER JOIN Orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_spending DESC
LIMIT 5;

-- Most Popular Product
SELECT p.product_name, COUNT(op.order_id) AS order_count
FROM Products p
LEFT JOIN Orders_Products op ON p.product_id = op.product_id
GROUP BY p.product_name
ORDER BY order_count DESC
LIMIT 1;